package org.aion;

import org.aion.avm.userlib.abi.ABIStreamingEncoder;

//TODO: it is expected that this file could be autogenerated by Aion toolchain in the future see https://github.com/aionnetwork/AVM/issues/401

public class AIPXXXEncoder {
  public static byte[] deploy(boolean startingFavoriteBool) {
    return new ABIStreamingEncoder()
        .encodeOneBoolean(startingFavoriteBool)
        .toBytes();
  }
  
  public static byte[] aipXXXGetFavoriteBool() {
    return new ABIStreamingEncoder()
        .encodeOneString("aipXXXGetFavoriteBool")
        .toBytes();
  }
  
  public static byte[] aipXXXSetFavoriteBool(boolean favoriteBool) {
    return new ABIStreamingEncoder()
        .encodeOneString("aipXXXGetFavoriteBool")
        .encodeOneBoolean(favoriteBool)
        .toBytes();
  }
}