package org.aion;

import avm.Blockchain;
import org.aion.avm.userlib.abi.ABIStreamingEncoder;
import avm.Address;

//TODO: it is expected that this file could be autogenerated by Aion toolchain in the future see https://github.com/aionnetwork/AVM/issues/401

public class AIPXXXSetter {


  
  public static String aipXXXGetFavoriteString(Address user) {
    return  Blockchain.getStorage(AIPXXXKeyValueStorage.favoriteStringKey(user)) == null 
            ? null
            : new String(Blockchain.getStorage(AIPXXXKeyValueStorage.favoriteStringKey(user)));
  }
  
  public static void aipXXXSetFavoriteString(String newFavoriteString) {
      Blockchain.putStorage(AIPXXXKeyValueStorage.favoriteStringKey(Blockchain.getCaller()), newFavoriteString.getBytes());
      AIPXXXEvents.aipXXXFavoriteStringSet(newFavoriteString);
  }
}
