package org.aion;

import avm.Blockchain;
import org.aion.avm.userlib.abi.ABIStreamingEncoder;

//TODO: it is expected that this file could be autogenerated by Aion toolchain in the future see https://github.com/aionnetwork/AVM/issues/401

public class AIPXXXSetter {

  private static String favoriteString = "Hello AIP";

  
  public static String aipXXXGetFavoriteString() {
    return favoriteString;
  }
  
  public static void aipXXXSetFavoriteString(String newFavoriteString) {
      favoriteString = newFavoriteString;
      Blockchain.putStorage(AIPXXXKeyValueStorage.favoriteStringKey(newFavoriteString), Blockchain.getCaller().toByteArray());
      AIPXXXEvents.aipXXXFavoriteStringSet(newFavoriteString);
  }
}
